package ru.aziattsev.pdm_system.entity;

public enum DocumentStatus {
    UNDEFINED,
    MODEL_MARKED_AS_NOT_READY,
    MODEL_MARKED_AS_READY,
    DRAWING_MARKED_AS_NOT_READY,
    DRAWING_MARKED_AS_READY,
    STANDARD_CONTROL_MARKED_AS_NOT_READY,
    STANDARD_CONTROL_MARKED_AS_READY,
    TECHNICAL_CONTROL_MARKED_AS_NOT_READY,
    TECHNICAL_CONTROL_MARKED_AS_READY,
    APPROVED_MARKED_AS_NOT_READY,
    APPROVED_MARKED_AS_READY,
}
